### ISSUE TITLE
test with multiple DBs

### ISSUE THREAD

**Issue by dalssoft** [endersoncosta/gotu2knex#7]
Even though Knex is supposed to support multiple DBs it is import to implement at least one more DB test runner in order to make sure this package is not tied to postgres.

**Comment by jhomarolo** [comment]
@dalssoft are you implementing this test? If not, I will perform here.

**Comment by dalssoft** [comment]
@jhomarolo go ahead

**Comment by endersoncosta** [comment]
Thanks!!!
